fixed lost log handling and tracking
illumio/cloud-operator pull request #37
Opened 2024-09-11 22:42 UTC by aaronIllumio

2024-09-11 23:17 UTC, rlenglet requested changes
Looks great! The code is cleaner and more readable.
One very minor nit.
Thank you!

2024-09-11 23:17 UTC, rlenglet commented on internal/controller/logger_manager.go
> +	lostLogsErr    error
Nit. Name these fields consistently.
```suggestion
	lostLogEntriesCount int
	lostLogEntriesErr   error
```

2024-09-11 23:48 UTC, aaronIllumio commented
> Looks great! The code is cleaner and more readable. One very minor nit. Thank you!

fixed

2024-09-12 00:42 UTC, rlenglet approved these changes

2024-09-12 00:50 UTC, merged