testing gha ability to push and build a cluster
illumio/cloud-operator pull request #96
Opened 2024-12-18 21:47 UTC by evanj80-illumio

2025-01-17 20:32 UTC, evanj80-illumio commented on .github/workflows/build_deploy_onboard.yml
> +name: Build, Deploy and Onboard Cloud Operator To Live Services
Ignore versions of some things in herer, going to go through GHA and fix versioning

2025-01-17 21:43 UTC, evanj80-illumio commented on cloud-operator/values.yaml
IMO this should have been **false** to begin with. Making the change in this PR

2025-01-17 21:45 UTC, evanj80-illumio commented on cmd/main.go
> +	if envConfig.RunningGHA {
This is required since we create the cluster first in GHA and the go test -v command needs time to spin up since its installs all of the required go packages. I think there may be a better version of this, maybe pre install go files as part of a GHA step. let me know what you think

2025-01-18 01:06 UTC, rlenglet commented on fakeserver/fakeserver_integration_test.go
> +// Simulating a client interacting with the gRPC server
```suggestion
// TestFakeServerConnectionSuccesfulAndRetry tests a client connecting to the gRPC server
```

2025-01-18 01:07 UTC, rlenglet commented on fakeserver/fakeserver_integration_test.go
> +	time.Sleep(5 * time.Second)
Why this sleep?

2025-01-18 01:07 UTC, rlenglet commented on fakeserver/fakeserver_integration_test.go
> +	time.Sleep(2 * time.Second)
Why this sleep? This seems brittle. Can't you use a WaitGroup or something like that?

2025-01-18 01:07 UTC, rlenglet commented on fakeserver/fakeserver_integration_test.go
> +	time.Sleep(2 * time.Second)
Same here. Why this sleep?

2025-01-18 01:08 UTC, rlenglet commented on integration-testing/onboard_test.go
> +package integrationtesting
Add the copyright header.

2025-01-21 18:22 UTC, evanj80-illumio commented on fakeserver/oauth2_token_endpoint.go
> +func startOAuth2HTTPServer(address string, cert tls.Certificate, authService *AuthService) (*http.Server, error) {
Was trying to be more file specific but your right. Also was a mistake to delete comment. Did not realize I had.

2025-02-03 18:03 UTC, rlenglet requested changes
Looks good. Some more minor comments.

2025-02-03 18:03 UTC, rlenglet commented on integration-testing/onboard_test.go
> +	body := map[string][]string{
It would be more readable to define a `struct`s with a `json:"..."` tag on each field than to create JSON objects by hand.
Like you did for `ClustersResponse` above.

2025-02-07 01:47 UTC, evanj80-illumio commented on .github/workflows/integration_fakeserver_tests.yml
> +          ONBOARDING_ENDPOINT: "https://192.168.49.1:50053/api/v1/k8s_cluster/onboard"
I looked into it and it seems more trouble then worth it

2025-02-07 01:47 UTC, evanj80-illumio commented on cloud-operator/values.yaml
> +  enabled: false
https://github.com/illumio/cloud-operator/pull/119

2025-02-07 23:42 UTC, rlenglet requested changes
Looks good!
I just have a few minor nits.

2025-02-07 23:42 UTC, rlenglet commented on fakeserver/main.go
> +	aud := "192.168.65.254:50051"
Is it ok to hardcode this IP address, instead of keeping the command-line flag?
Doesn't that prevent using `fakeserver` for interactive dev testing now?

2025-02-07 23:42 UTC, rlenglet commented on integration-testing/onboard_test.go
> +func buildRequest(method, url string, body io.Reader, config Config) (*http.Request, error) {
NIt. I think "new" is more idiomatic.
```suggestion
func newRequest(method, url string, body io.Reader, config Config) (*http.Request, error) {
```

2025-02-07 23:42 UTC, rlenglet commented on integration-testing/onboard_test.go
> +	baseURL := "https://cloud.illum.io/api/v1/k8s_cluster" // Replace with actual URL
Is this comment still relevant?
```suggestion
	baseURL := "https://cloud.illum.io/api/v1/k8s_cluster"
```

2025-02-07 23:42 UTC, rlenglet commented on integration-testing/onboard_test.go
> +	var uuids []string
```suggestion
	uuids := make([]string, 0, len(clusters))
```

2025-02-07 23:42 UTC, rlenglet commented on integration-testing/onboard_test.go
> +	fmt.Println(clusters)
```suggestion
```

2025-02-07 23:42 UTC, rlenglet commented on integration-testing/onboard_test.go
> +	fmt.Println(uuids)
```suggestion
```

2025-02-07 23:42 UTC, rlenglet commented on integration-testing/onboard_test.go
> +func extractUUIDs(clusters []Cluster) []string {
```suggestion
func getClusterIDs(clusters []Cluster) []string {
```

2025-02-10 01:01 UTC, evanj80-illumio commented on fakeserver/main.go
> +	aud := "192.168.65.254:50051"
So when you are running the fakeserver through main.go it injects this IP so that it will work locally

2025-02-10 01:24 UTC, evanj80-illumio commented on .github/workflows/build_deploy_onboard.yml
Will need to set env vars for this test @rlenglet

2025-02-10 01:25 UTC, evanj80-illumio commented on .github/workflows/build_deploy_onboard.yml
> +          push: true
Without push: true it wont push the temp image to GHCR

2025-02-11 01:37 UTC, rlenglet approved these changes

2025-02-11 01:37 UTC, rlenglet commented on .github/workflows/build_deploy_onboard.yml
> +            ghcr.io/${{ github.repository }}:${{ github.sha }}
It would be better to use the `docker/metadata-action` to determine the tags:
https://github.com/docker/metadata-action
In case this is executed in the context of a PR, it generates a tag like `pr-96`, which would make it much easier to find and to distinguish from production image tags.

OK to do that later if you want.

2025-02-11 01:37 UTC, rlenglet commented on .github/workflows/build_deploy_onboard.yml
> +            ghcr.io/${{ github.repository }}:${{ github.sha }}
Feel free to close if you prefer to move to that in another PR.

2025-02-11 02:47 UTC, merged